[functions.cancel-order]
verify_jwt = false

[functions.get-token-data]
verify_jwt = false

[functions.verify-token]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.create-recharge]
verify_jwt = false

[functions.create-refund]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.get-messages]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-action]
verify_jwt = false
